# This is a basic workflow to help you get started with Actions
name: Deploy Website

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push]

# A workflow run in made up of one or more jobs that can run sequentially or in parallel.
jobs:
  
  # This workflow contains a single job called "build"
  build:  
    name: Deploying to surge
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v2
        
        
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      - name: Install Surge
        run: npm install -g surge
        
      - name: Run surge
        run: surge ./ waseem602_start.surge.sh --token ${{ secrets.SURGE_TOKEN}}
